version: '3'

services:
  httpd:
    container_name: lighttpd
    image: nicoroud/docker-alpine-lighttpd
    restart: always
    networks:
      - default
    expose:
      - "80"
    environment:
      - TZ=Europe/Paris
      - VIRTUAL_HOST=domain.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=domain.com
      - LETSENCRYPT_EMAIL=your@email.com
    volumes:
      - /var/www/html:/var/www
      - ./lighttpd:/etc/lighttpd
networks:
  default:
    external:
      name: webproxy
